# Generated by Django 5.2 on 2025-04-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("holding", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="holding",
            table="holding",
        ),
    ]
