# Generated by Django 5.2.1 on 2025-05-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holding', '0004_remove_holding_type_holding_market_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='market_type',
            field=models.CharField(choices=[('CRYPTO', 'Crypto'), ('STOCK', 'Stock')]),
        ),
    ]
