version: 0.0
os: linux
files:
  - source: /
    destination: /ubuntu/home/
permissions:
  - object: /home/ubuntu/Jusicool-Server
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu