# Generated by Django 5.2.1 on 2025-06-02 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardpost',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
