# Generated by Django 5.2.1 on 2025-07-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0006_boardlike"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="board",
        ),
    ]
