# Generated by Django 5.2.1 on 2025-07-10 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0007_rename_post_comment_board"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="boardlike",
            old_name="post",
            new_name="board",
        ),
        migrations.AlterUniqueTogether(
            name="boardlike",
            unique_together={("user", "board")},
        ),
    ]
