# Generated by Django 5.2 on 2025-04-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accounthistory",
            old_name="type",
            new_name="history_type",
        ),
    ]
