# Generated by Django 5.2 on 2025-04-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_type_accounthistory_history_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='krw_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
