# Generated by Django 5.2 on 2025-04-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_price"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="order",
            table="order",
        ),
    ]
