# Generated by Django 5.2.1 on 2025-06-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_price_order_execute_price_order_reserve_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='execute_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
