# Generated by Django 5.2 on 2025-04-27 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("korean_name", models.CharField(max_length=255, unique=True)),
                ("english_name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("CRYPTO", "Crypto"), ("STOCK", "Stock")], max_length=6
                    ),
                ),
            ],
            options={
                "db_table": "market",
            },
        ),
    ]
