# Generated by Django 5.2 on 2025-04-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="market",
            field=models.CharField(default="None", max_length=255),
            preserve_default=False,
        ),
    ]
