# Generated by Django 5.2.1 on 2025-05-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_market_type_market_market_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='english_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
