# Generated by Django 5.2.1 on 2025-07-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_alter_market_market_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="market",
            index=models.Index(fields=["market"], name="market_market"),
        ),
    ]
